version: "3.9"

services:

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: project_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      project_ipvlan_net:
        ipv4_address: 192.168.100.11

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_backend
    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

    command: node src/server.js   # ✅ important

    depends_on:
      db:
        condition: service_healthy

    networks:
      project_ipvlan_net:
        ipv4_address: 192.168.100.10


volumes:
  pg_data:

networks:
  project_ipvlan_net:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1